# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TLDRecipe
email: hello@tldrecipe.co
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.tldrecipe.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TLDRecipe
instagram_username: TLDRecipe
timezone: America/New_York

# Dev purposes (view locally on mobile)
host: 0.0.0.0

# Post Excerpts Enanabled
show_excerpts: true

# Hardcode Navigation Link Order
header_pages:
  # - about.md
  # - upcoming-events.md

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Assign Static File Path Variables (reference scripts.html)
defaults:
  - scope:
      path: "scripts"
    values:
      script: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: [ Gemfile, Gemfile.lock, node_modules, package.json, package-lock.json, gulpfile.js]
